name: test

on:
  pull_request:
    types:
      - closed
    branchs:
      - main
    paths:
      - "src/test/**"

jobs:
  git_diff_test:
    name: git diff test
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Notice diff files
        id: skip-test
        run: |-
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }} --depth=1
          diff=$(git diff --name-only HEAD ${{ github.base_ref }} --relative -- ./src | wc -l)
          echo "::notice diff: $diff"
