name: List Updated Files on Merge

on:
  pull_request:
    types: [closed]

jobs:
  list-files:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out merged code with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Get list of updated files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          echo "$CHANGED_FILES" | while read file; do
            echo "Updated file: $file"
          done
