name: test

on:
  pull_request:
    branchs:
      - main
    paths:
      - "src/test/**"

jobs:
  git_diff_test:
    name: git diff test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: bash
        working-directory: src
    
    steps:
      - name: Fetch Base Branch Latest Commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 1

      # マージブランチのチェックアウト（デフォはgithub.shaに向いてる）
      - name: Checkout Pull Request
        uses: actions/checkout@v3

      - name: Notice diff files
        id: skip-test
        run: |-
          diff=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}..${{ github.sha }})
          echo "::notice diff: $diff"
